# Generated by Django 2.2.16 on 2022-06-10 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Home Page Setting',
                'verbose_name_plural': 'Home Page Settings',
                'db_table': 'homepagesettings_en',
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sitename', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'Site Setting',
                'verbose_name_plural': 'Site Settings',
                'db_table': 'sitesettings_en',
            },
        ),
        migrations.CreateModel(
            name='SocialSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=20)),
                ('url', models.URLField()),
            ],
            options={
                'verbose_name': 'Social Setting',
                'verbose_name_plural': 'Social Settings',
                'db_table': 'socialsettings_en',
            },
        ),
    ]
