# Generated by Django 2.2.16 on 2022-06-10 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite_en', '0004_auto_20220610_2009'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepagesettings',
            options={},
        ),
        migrations.AlterModelOptions(
            name='sitesettings',
            options={},
        ),
        migrations.AlterModelOptions(
            name='socialsetting',
            options={},
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='editor_choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='editor_choice_en', to='news.News'),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='hot_news',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hot_news_en', to='news.News'),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='post_catalog_five',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_catalog_five_en', to='news.Category'),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='post_catalog_four',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_catalog_four_en', to='news.Category'),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='post_catalog_one',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_catalog_one_en', to='news.Category'),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='post_catalog_three',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_catalog_three_en', to='news.Category'),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='post_catalog_two',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_catalog_two_en', to='news.Category'),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='trending',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trending_en', to='news.News'),
        ),
        migrations.AlterModelTable(
            name='homepagesettings',
            table=None,
        ),
        migrations.AlterModelTable(
            name='sitesettings',
            table=None,
        ),
        migrations.AlterModelTable(
            name='socialsetting',
            table=None,
        ),
    ]
