# Generated by Django 2.2.16 on 2022-06-10 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_en', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={},
        ),
        migrations.AlterModelTable(
            name='news',
            table=None,
        ),
    ]
