# Generated by Django 2.2.16 on 2022-06-09 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20220420_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='slug',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
