# Generated by Django 3.0.2 on 2020-08-04 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_blog_it', '0002_auto_20200804_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
